---
# Lint directives.
lint:
  # Linter directories to walk.
  directories:
    # The specific directories to exclude.
    exclude:
      # NOTE: UNIX paths will be properly accepted by both UNIX and Windows.
      - proto/google
      - proto/protoc-gen-openapiv2

  # Linter rules.
  # Run `protolint list` to see all available rules.
  rules:
    # Determines whether or not to include the default set of linters.
    no_default: true

    # Set the default to all linters. This option works the other way around as no_default does.
    # If you want to enable this option, delete the comment out below and no_default.
    # all_default: true

    # The specific linters to add.
    # add:
    #   - FIELD_NAMES_LOWER_SNAKE_CASE
    #   - MESSAGE_NAMES_UPPER_CAMEL_CASE

    # The specific linters to remove.
    # remove:
    #   - RPC_NAMES_UPPER_CAMEL_CASE

  # Linter rules option.
  rules_option:
    # MAX_LINE_LENGTH rule option.
    max_line_length:
      # Enforces a maximum line length
      max_chars: 150
      # Specifies the character count for tab characters
      tab_chars: 2