basePath: /
definitions:
  handler.errorResponse:
    properties:
      message:
        type: string
    type: object
  mnemosyne.Request:
    properties:
      texts:
        items:
          type: string
        type: array
    type: object
  mnemosyne.Response:
    properties:
      texts:
        items:
          type: string
        type: array
      version:
        type: string
    type: object
host: localhost:8000
info:
  contact: {}
  description: API Server for Mnemosyne application
  title: Mnemosyne App API
  version: "1.0"
paths:
  /mnemosyne:
    post:
      consumes:
      - application/json
      description: Get answer by mnemosyne command
      operationId: mnemosyne-request
      parameters:
      - description: Body request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/mnemosyne.Request'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/mnemosyne.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/mnemosyne.Response'
      summary: Mnemosyne
      tags:
      - Mnemosyne
swagger: "2.0"
